### ISSUE TITLE
Converting to onnx

### ISSUE THREAD

**Issue by MetaDev** [anibali/dsntnn#10]
I would like to convert the model to ONNX format but, the operators flip and linspace are not supported. Is there a workaround for this?
Thanks

**Comment by anibali** [comment]
If you are using DSNT at the output, one option is to save the model up until (but excluding) the DSNT-related operations. Since those layers don't have weights anyway, saving them is not important. Kind of like how you don't need to save the loss function.

**Comment by anibali** [comment]
This is effectively a duplicate of https://github.com/anibali/dsntnn/issues/9
