### ISSUE TITLE
Get confidence of prediciton per regressed coordinate

### ISSUE THREAD

**Issue by simonhessner** [anibali/dsntnn#11]
Hi,

first of all: I really like the DSNT layer. It works perfectly and the idea is really cool :)

However, what would be really useful for my application, is a way to get the confidence of my model that the coordinate regressed by DSNT is correct. When looking at the heatmaps, the confidence should be very high when the heatmap values are close to 1 at the predicted position and close to 0 everywhere else. The confidence should be low when it there is a large patch in the heatmap that has a low confidence and then in the middle of this patch there is one point with a slightly higher confidence.

So I guess what I am looking for is a way to derive the standard deviation of a Gaussian which has its center at the position that is predicted by DSNT. And then I would have to transform the deviation to a confidence value between 0 and 1.

In the end I want to have n coordinates that have 3 values: x,y, confidence

Is there an easy way to do this with the functions already provided by DSNT?

Best,
Simon

**Comment by simonhessner** [comment]
I think I could use _divergence_reg_losses with different `sigma_t` values and `mu_t` as the regressed coordinate and then see which `sigma_t` has the lowest loss. That would be kind of a brute force approach, but better than nothing

**Comment by anibali** [comment]
If you look at the `variance_reg_losses` function you can find an example of calculating the variance of heatmaps:

https://github.com/anibali/dsntnn/blob/4f20f5a85b56d007adef51e5158f5a6dca92794f/dsntnn/__init__.py#L233-L262

I haven't tried using it this way myself, but it could be possible to use this sort of calculation as a proxy for confidence.

**Comment by simonhessner** [comment]
Very nice, have not seen this function. This seems to work pretty good in my first tests. Just have to find a nice way to transform it into values between 0 and 1, but I'll figure it out. Thank you!

**Comment by briantse100** [comment]
@anibali, I use the function variance_reg_losses() with to get confidence. But the confidence is 0.05 very low with unnormalized_heatmaps and  3.9954e+08 very high with normalized_heatmaps. How to get normal landmark confidence?  if I  make traditional gauss heatmap like figure2b in the paper, the heatmap value is [0, 1], and I will try it.

**Comment by anibali** [comment]
You will need to calibrate the outputs from `variance_reg_losses` yourself. Keep in mind that it should have an inverse relationship with confidence (a large value indicates low confidence). It should be used with normalised heatmaps.

Note that this is not something that I have tried myself, so you will need to do some experimenting.

**Comment by briantse100** [comment]
@anibali Thanks your replay. I have cablibrated the outputs and experimented. In the example of  basic_usage.md, add three different points [24, 27] [28, 32] [32, 15]. But the three points output values have big difference, eg, 0.2, 0.02, 0.12. Is it normal? Cablibrate by abs(output - output_mean)/(max_output - min_output) and is it right? If only one point as input, this cablibrate method doesnot work.

If it can make gauss like function [gaussian(img, pt, sigma)](https://github.com/princeton-vl/pose-hg-train/blob/master/src/pypose/draw.py) ? And I have a try.

**Comment by anibali** [comment]
You just have to experiment with your actual data. There is no way to tell whether the spread of numbers is meaningful for three points, you have to observe what the values are like for both good and bad predictions to see whether they are correlated.

**Comment by briantse100** [comment]
ok, thanks, I have a try.
