### ISSUE TITLE
A question about the input and target

### ISSUE THREAD

**Issue by YuQi9797** [anibali/dsntnn#18]
Do the input image and target heat map need to be normalized to the range (-1,1) before it can be used? Because I saw you write it: 
```
The input and target need to be put into PyTorch tensors. Importantly, the target coordinates are normalized so that they are in the range (-1, 1). The DSNT layer always outputs coordinates in this range.
```

**Comment by YuQi9797** [comment]
```
raccoon_face_tensor = torch.from_numpy(raccoon_face).permute(2, 0, 1).float()

input_tensor = raccoon_face_tensor.div(255).unsqueeze(0)

input_var = input_tensor.cuda()
```
the input_var is normalized (0~1).

But I don't know the target_var.
```
eye_coords_tensor = torch.Tensor([[[eye_x, eye_y]]])

target_tensor = (eye_coords_tensor * 2 + 1) / torch.Tensor(image_size) - 1

target_var = target_tensor.cuda()
```

If I want to use DSTNN, what do I need to do with the input and output?

**Comment by anibali** [comment]
This library offers the ability to choose whether you would like to calculate normalised coordinates or pixel coordinates via the `normalized_coordinates` parameter of the `dsnt` function. If you leave this as its default (`False`), then you will need to normalise the target. You can convert between normalised and pixel coordinates using the `normalized_to_pixel_coordinates` and `pixel_to_normalized_coordinates` functions.

**Comment by YuQi9797** [comment]
I would like to ask, if I use DSTNN to calculate coordinates, do I need to do any standardization on my input and the heat map label?

At present, my image is standardized with [128,128, 128] as the mean value, [256,256,256] as the variance, and the label is the Gaussian distribution of the key points in the image position.

**Comment by anibali** [comment]
The heatmap which goes into `dsnt` is expected to be a valid probability distribution over locations, so all pixels must be be non-negative and sum to 1. You can achieve this using `flat_softmax` on the network's output. Please refer to the basic usage guide for an example. You do not need to create the Gaussian distribution for your targets, the functions in this library take 2D keypoint locations.
