### ISSUE TITLE
increase batch size 1 to 16, it made wrong result.

### ISSUE THREAD

**Issue by Lagom92** [anibali/dsntnn#21]
Hello

now i want to make landmark detection.
so i use dsntnn.
when i set batch size=1 , result is good
but
if batch size=16
result points are gathered in one place.

why is that? What should i do??

**Comment by anibali** [comment]
You haven't provided much detail here. What is the complete shape of the tensor that you are passing into the DSNT function when using batch size 16? How many keypoints are you trying to predict?

**Comment by Lagom92** [comment]
I want to predict 16 points. 
I edit FCN's input channel 3 to 1.

in my code.
...

print(img.shape)
coords, heatmaps = model(img)

...

torch.Size([16, 1, 224, 224])

**Comment by anibali** [comment]
What is the shape of the heatmaps (FCN output)?

**Comment by Lagom92** [comment]
print(heatmaps.shape)

torch.Size([16, 16, 224, 224])

**Comment by anibali** [comment]
You probably have a problem somewhere in your code. I recommend trying a batch size that is quite different from your number of keypoints (e.g. 5) since you may be hiding an incorrect permutation of axes somewhere. Then take a careful look at any view/reshape operations that you might be using.

**Comment by Lagom92** [comment]
Ok i set batch size = 8

now
```
coords, heatmaps = model(img)

print(img.shape)
print(coords.shape)
print(heatmaps.shape)

torch.Size([8, 1, 224, 224])
torch.Size([8, 16, 2])
torch.Size([8, 16, 224, 224])
```

but i don't know what this means.

```
 Then take a careful look at any view/reshape operations that you might be using.
```

May you explain more thoroughly to me?

Which part should I watch in my code?
(e.g. dataset? loss function?)

**Comment by anibali** [comment]
I'm sorry, but unless you can produce a specific example of an issue with DSNTNN I'm going to have to close this issue. There are just too many possible reasons why your particular project might be failing.
