### ISSUE TITLE
For the normalized_linspace function

### ISSUE THREAD

**Issue by Jerrrrry-Zhu** [anibali/dsntnn#22]
According to the paper，Is it should be 
```python
first = -(length + 1.0) / length
```
![1661309340952](https://user-images.githubusercontent.com/61321296/186309448-73cded62-24aa-4761-aeac-a2b2e473ed5b.png)
![1661309536682](https://user-images.githubusercontent.com/61321296/186309792-b9515f64-89b5-46c3-abc2-f29287a7a2de.png)

**Comment by anibali** [comment]
That is the difference between 0-based and 1-based indexing. The paper uses 1-based (mathematics convention), the code uses 0-based (numpy convention).

e.g. applying the 0-based "correction" to the first equation gives `(2(j-1)-(n+1))/n = (2j - 2 - (n+1)) / n = (2j - (n-1)) / n`

**Comment by Jerrrrry-Zhu** [comment]
Got it,thanks for your reply
