### ISSUE TITLE
Pip install fails

### ISSUE THREAD

**Issue by MR2011** [anibali/dsntnn#3]
Installing dsntnn with pip throws this error:

> Could not find a version that satisfies the requirement dsntnn (from versions: )
No matching distribution found for dsntnn

My pip3 version: 10.0.1
Python version: 3.5.2
Os: Mac OS X 10.13.5 High Sierra

**Comment by anibali** [comment]
Oops, I forgot to actually upload the release to PyPI. It should work now: https://pypi.org/project/dsntnn/
