### ISSUE TITLE
Question re. occluded or missing points in training data

### ISSUE THREAD

**Issue by seanbow** [anibali/dsntnn#4]
When training a model that outputs a heatmap, training data with missing or occluded points are easily handled by setting the target output to be a heatmap of all zeros. With the DSNT layer, how can this be handled? An all-zero heatmap corresponds corresponds to target coordinates of [0,0] here, but so does a point very well localized in the center of the image.

**Comment by anibali** [comment]
You can simply refrain from applying loss to those specific heatmaps during training, which means that the heatmaps will not be biased towards any particular representation in the missing label case. I would not recommend using an all-zero representation for the reason you mention.

**Comment by guker** [comment]
> 您可以简单地避免在训练期间对那些特定的热图应用损失，这意味着热图不会偏向于缺少标签情况下的任何特定表示。出于您提到的原因，我不建议使用全零表示。

make sense
