### ISSUE TITLE
Use generated 2d-guassion heatmap as the regularization.

### ISSUE THREAD

**Issue by yuanyuanli85** [anibali/dsntnn#5]
I took a look at the paper, and curious about the regularization part, such as KL, JS..etc.  I am wondering if it is possible to use 2d-guassion heatmap generated from ground truth as the regularization.  What do you think of that?

**Comment by anibali** [comment]
That is essentially how my code works already. For the divergence-based regularisation terms (KL and JS), the divergence is calculated between the ideal, ground truth-based 2D Gaussian and the predicted heatmap.

**Comment by yuanyuanli85** [comment]
thank you for your answers.
